### ISSUE TITLE
admin.html: Line 65; id.name

### ISSUE THREAD

**Issue by QuietEvolver** [EwRicklefs/Watch-the-screens#43]
@CPJanz 
Good morning Carl, the id is missing a lower case "L" ~ thanks
line65 admin.html    <h5 class="modal-title" id="gobal-post-label">Create Global Post</h5>

**Comment by QuietEvolver** [comment]
@CPJanz: Please feel free to close this project 'Question' after answered; Many thanks, Carl

**Comment by CPJanz** [comment]
good catch! fixed and submitted
